app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::group(['prefix' => '/', 'namespace' => 'Frontend'], function() {

	Route::get('/', 'PageController@home');

	Route::get('beli/{slug}', 'CartController@tambahProduk');

	Route::get('tambahkan/{slug}/{quantity?}', 'CartController@tambahProduk');

	Route::get('gak-jadi-beli/{slug}', 'CartController@hapusProduk');

	Route::get('kurangkan/{slug}/{quantity?}', 'CartController@kurangProduk');

	Route::get('cart', 'CartController@index');

	Route::get('checkout', 'CheckoutController@index');

	Route::get('checkout/without_registration', 'CheckoutController@withoutRegistration');

	Route::post('checkout','CheckoutController@postCheckout');
	
	Route::get('checkout/{kode_pesanan}', 'CheckoutController@getCheckout');

	Route::get('checkout/{kode_pesanan}', 'CheckoutController@getCheckout');

	Route::post('cart', 'CartController@updateCart');

	Route::post('cart/info', 'CartController@updateInfo');

	Route::post('konfirmasi_pembayaran', 'PageController@checkPaymentConfirmation');

	Route::get('konfirmasi_pembayaran/{kode_pesanan?}', 'PageController@paymentConfirmation');

	Route::post('konfirmasi_pembayaran/{kode_pesanan}', 'PageController@postPaymentConfirmation');

	Route::post('lacak', 'PageController@checkTracking');

	Route::get('lacak/{kode_pesanan?}', 'PageController@tracking');

	Route::get('contact', 'PageController@getContact');

	Route::post('contact', 'PageController@postContact');
});

Route::get('home', function () {
	if (request()->session()->has('checkout')) {
		request()->session()->forget('checkout');
		return redirect('checkout');
	}

	if (auth()->check() && auth()->user()->is_admin) {
		return redirect('admin');
	}

	return redirect('/');
});

Route::controller('auth', 'Auth\AuthController');
Route::controller('reset', 'Auth\PasswordController');

Route::group(['prefix' => 'shop', 'namespace' => 'Frontend'], function() {

	Route::get('/', 'PageController@shop');

	Route::get('search/{keyword?}', 'PageController@shopBySearch');

	Route::get('{slug}', 'PageController@shopByKategori');

	Route::get('merk/{slug}', 'PageController@shopByBrand');

});



Route::group(['prefix' => 'ongkir'], function() {
	Route::get('propinsi', function() {
		$id = request()->get('id', null);
		if ($id !== null && null != $propinsi = \App\Propinsi::find($id)) return $propinsi;
		$q = request()->get('q', '');
		$data = \App\Propinsi::where('propinsi', 'like', '%'.$q.'%')->get();
		return $data;
	});

	Route::get('kota', function() {
		$id = request()->get('id', null);
		if ($id !== null && null != $kota = \App\Kota::find($id)) return $kota;
		$q = request()->get('q', '');
		$propinsi_id = request()->get('prop', '%');
		$data = \App\Kota::where('propinsi_id', 'like', $propinsi_id)->where('kota', 'like', '%'.$q.'%')->get();
		return $data;
	});

	Route::get('cek', function() {
		$key = '41c4c7f98ebf86849fb90c304093f145';
		$origin = '348'; // id kota berdasarkan tabel di database
		$courier = request()->get('courier', 'jne');
		$destination = request()->get('kota');
		$weight = request()->get('weight');

		$cekCode = request()->get('code', null);
		if ($cekCode != null) {
			$codes = explode('-', $cekCode);
			$courier = $codes[0];
			$serviceCode = $codes[1];
		}

		$client = new GuzzleHttp\Client();
		$res = $client->request('POST', 'http://api.rajaongkir.com/starter/cost', [
				    'headers' => ['key' => $key, 'content-type' => 'application/x-www-form-urlencoded'],
				    'form_params' => compact('origin', 'destination', 'weight', 'courier'),
				]);

		$html = $res->getBody();

		$result = json_decode($html);

		if (!isset($result->rajaongkir->results) or $result->rajaongkir->results == null) return [];

		$kurirs = $result->rajaongkir->results;

		// return $kurirs;

		$data = [];

		foreach ($kurirs as $kurir) 
		{
			foreach ($kurir->costs as $layanan) 
			{
				if (!isset($layanan->cost) or count($layanan->cost) == 0) continue; 

				$cost = $layanan->cost; 

				$service = [];

				$service['text'] = strtoupper($kurir->code) . ' ' . $layanan->service . (!empty($etd = $layanan->cost[0]->etd) ? ' ('.$etd.' hari) ' : ''). ' - Rp '.number_format($layanan->cost[0]->value, 0, ',', '.');

				$service['id'] = $kurir->code.'-'.$layanan->service;

				$service['cost'] = $layanan->cost[0]->value;


				$service['cost_rupiah'] = 'Rp '.number_format($layanan->cost[0]->value, 0, ',', '.');

				// if ($courier == $kurir->code && $serviceCode == $layanan->service) return $service;

				$data[] = $service;
			}
		}
		return $data;
	});
});

Route::get('search', function () {
	return redirect('shop/search/'.request()->get('keyword', ''));
});

Route::get('tes', function(App\Http\Controllers\BaseController $base) {
	return $base->global_params['nama_toko'];
});

Route::group(['prefix' => 'admin', 'namespace' => 'Backend', 'middleware' => 'admin'], function() {
    
	Route::get('/', 'PageController@home');
	Route::post('brand/data.json', 'BrandController@datajson');
	Route::resource('brand', 'BrandController');

	Route::post('customer/data.json', 'CustomerController@datajson');
	Route::resource('customer', 'CustomerController');

	Route::post('kategori/data.json', 'KategoriController@datajson');
	Route::resource('kategori', 'KategoriController');
	
	Route::post('produk/data.json', 'ProdukController@datajson');
	Route::resource('produk', 'ProdukController');
	
	Route::post('pesanan/data.json', 'PesananController@datajson');
	Route::get('pesanan', 'PesananController@index');
	Route::get('pesanan/proses/{id}', 'PesananController@getProsesPesanan');
	Route::post('pesanan/proses/{id}', 'PesananController@postProsesPesanan');
	Route::controller('pesanan', 'PesananController');

	Route::post('setting/data.json', 'ParamController@datajson');
	Route::resource('setting', 'ParamController');

	Route::post('pembayaran/data.json', 'PembayaranController@datajson');
	Route::resource('pembayaran', 'PembayaranController');

	Route::post('metode_pembayaran/data.json', 'MetodePembayaranController@datajson');
	Route::resource('metode_pembayaran', 'MetodePembayaranController');

	Route::post('pesan/data.json', 'PesanController@datajson');
	Route::resource('pesan', 'PesanController');

	Route::post('foto_produk/data.json', 'FotoProdukController@datajson');
	Route::resource('foto_produk', 'FotoProdukController');

});

app/Pembayaran.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pembayaran extends BaseModel
{
    const FOTO_PATH = 'asset/bukti_pembayaran/';
  
    protected $fillable = [
		'pesanan_id',
		'metode_pembayaran_id',
		'jumlah',
		'bukti',
		'verified_at',
    ];

    protected $dependencies  = ['pesanan', 'metode_pembayaran'];

    protected $dates = ['verified_at'];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model)
        {
            $model->process();
        });

        static::saving(function ($model)
        {
            $model->process();
        });

        static::deleted(function ($model)
        {
            $model->deleteImages();
        });
    }

    protected function process()
    {
        if (request()->has('pesanan')) $this->attributes['pesanan_id'] = request()->get('pesanan');
        if (request()->has('metode_pembayaran')) $this->attributes['metode_pembayaran_id'] = request()->get('metode_pembayaran');
        unset($this->attributes['pesanan']);
        unset($this->attributes['metode_pembayaran']);

        if (request()->hasFile('bukti') && request()->file('bukti')->isValid())
        {
            $destinationPath = public_path(static::FOTO_PATH);
            $fileName = str_slug($this->produk.' '.date('YmdHis')) . '.' . request()->file('bukti')->getClientOriginalExtension();
            $result = request()->file('bukti')->move($destinationPath, $fileName);
            if ($result) {
                $this->bukti = $fileName;
            }
        }   
        else 
        {
            if ($this->bukti) $this->bukti = $this->bukti;
        }
    }

    protected function deleteImages()
    {
        if ($this->bukti && $this->id && is_file($exist_file = public_path(static::FOTO_PATH).$this->getOriginal('bukti'))) unlink($exist_file);
    }

    public function getJumlahRupiahAttribute()
    {
        return number_format($this->jumlah , 0, ',' , '.');
    }

    public function pesanan()
    {
    	return $this->belongsTo(Pesanan::class)->with('customer');
    }

    public function metode_pembayaran()
    {
    	return $this->belongsTo(MetodePembayaran::class);
    }
}

app/Produk.php
<?php

namespace App;

use Carbon\Carbon;
use App\BaseModel;
use App\Brand;
use App\Kategori;

class Produk extends BaseModel
{
    const FOTO_PATH = 'asset/produk/';

    protected $fillable = [
            'produk',
            'slug',
            'kategori_id',
            'kategori',
            'harga',
            'harga_diskon',
            'deskripsi',
            'netto',
            'foto',
            'brand_id',
            'brand',
            'stock',
    ];

    protected $dependencies = [
        'kategori', 'brand'
    ];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model)
        {
            $model->process();
        });

        static::saving(function ($model)
        {
            $model->process();
        });

        static::deleting(function ($model)
        {
            $model->deleteAllImages();
        });
    }

    protected function process()
    {
        if (request()->has('kategori')) $this->attributes['kategori_id'] = request()->get('kategori');
        if (request()->has('brand')) $this->attributes['brand_id'] = request()->get('brand');
        unset($this->attributes['kategori']);
        unset($this->attributes['brand']);

        if (request()->hasFile('foto') && request()->file('foto')->isValid())
        {
            $this->deleteImages();

            $destinationPath = public_path(static::FOTO_PATH);
            $fileName = str_slug($this->produk.' '.date('YmdHis')) . '.' . request()->file('foto')->getClientOriginalExtension();
            $result = request()->file('foto')->move($destinationPath, $fileName);
            if ($result) {
                $this->foto = $fileName;
            }
        }   
        else 
        {
            if ($this->foto) $this->foto = $this->foto;
        }
    }

    protected function deleteImages()
    {
        if ($this->foto && $this->id && is_file($exist_file = public_path(static::FOTO_PATH).$this->getOriginal('foto'))) unlink($exist_file);
    }

    protected function deleteAllImages()
    {
        $this->deleteImages();

        foreach ($this->fotos as $foto) {
            $foto->delete();
        }
    }

    public function getTitleOfFields($fields = [])
    {
        $theKeys = array_flip($this->fillable);
        $titles = array_except($this->fillable, [$theKeys['kategori'], $theKeys['brand']]);
        return parent::getTitleOfFields($titles);
    }

    public function getHargaRupiahAttribute()
    {
        return number_format($this->harga , 0, ',' , '.');
    }

    public function getHargaDiskonRupiahAttribute()
    {
        return number_format($this->harga_diskon , 0, ',' , '.');
    }

    public function getIsSaleAttribute()
    {
        return $this->harga_diskon > 0 && $this->harga_diskon < $this->harga;
    }

    public function getIsNewAttribute()
    {
        return $this->created_at->diffInDays(Carbon::now()) < (isset($this->global_params['lama_hari_produk_baru']) ? $this->global_params['lama_hari_produk_baru'] : 7);
    }

    public function rules()
    {
        if (!request()->has('slug')) request()->merge(['slug' => str_slug(request()->get('produk'))]);

    	return [
            'slug' => 'required|unique:produks,slug'.(($this->id != null) ? ','.$this->id : ''),
            'foto' => 'image|max:5120'
    	];
    }

    public function fotos()
    {
        return $this->hasMany(FotoProduk::class);
    }

    public function kategori()
    {
        return $this->belongsTo(Kategori::class);
    }

    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }

    public function pesanans()
    {
        return $this->belongsToMany(Pesanan::class, 'pesanan_details')->withPivot('pesanan_id', 'produk_id', 'quantity')->withTimestamps();
    }

}

app/Http/Controllers/Frontend/CartController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;

use App\Produk;
use App\Pesanan;
use App\Http\Requests;
use App\Http\Controllers\FrontendController;

class CartController extends FrontendController
{

    public function index(Request $request)
    {
        if ($request->wantsJson()) {
            $pesanan = $this->getCurrentPesanan();
            return $pesanan;
        }

        return view('frontend.cart');
    }

    protected function getCurrentPesanan()
    {
    	$pesanan = request()->session()->has('pesanan') ? Pesanan::with('produks')->find(request()->session()->get('pesanan')) : Pesanan::create();
        return $pesanan;
    }

    
    public function tambahProduk(Request $request, $slug, $quantity = null)
    {
        // dapatkan data quantity atau default = 1
        $quantity = ($quantity != null) ? $quantity : $request->get('quantity', 1);
        // dapatkan data produk
        $produk = Produk::where('slug', $slug)->first();
        // ambil data pesanan dari session atau buat baru
        $pesanan = $this->getCurrentPesanan();
        // tambahkan produk ke dalam pesanan
        $tambahProduk = $pesanan->tambahProduk($produk, $quantity);

        if ($tambahProduk === false)
        {
            alert()->error('Gagal menambahkan '.$quantity.' produk '.$produk->produk.' karena stok kurang. ', 'Update Cart Gagal')->autoClose(3600);

            return back();
        }

    	// update session 
    	$request->session()->put('pesanan', $pesanan->id);

    	// beri alert
    	alert()->success('Berhasil menambahkan '.$quantity.' produk '.$produk->produk.' ke dalam keranjang. ', 'Update Cart Success')->autoClose(3600);

    	// kembalikan ke halaman sebelumnya	
    	return back();
    }


    public function kurangProduk(Request $request, $slug, $quantity = null)
    {
        // dapatkan data quantity atau default = 1
        $quantity = ($quantity != null) ? $quantity : $request->get('quantity', 1);
        // dapatkan data produk
        $produk = Produk::where('slug', $slug)->first();
        // ambil data pesanan dari session atau buat baru
        $pesanan = $this->getCurrentPesanan();
        // tambahkan produk ke dalam pesanan
        $pesanan->kurangProduk($produk, $quantity);

        // update session 
        $request->session()->put('pesanan', $pesanan->id);

        // beri alert
        alert()->success('Berhasil mengurangi '.$quantity.' produk '.$produk->produk.' dari keranjang. ', 'Update Cart Success')->autoClose(3600);

        // kembalikan ke halaman sebelumnya 
        return back();
    }

    public function hapusProduk(Request $request, $slug)
    {
        return $this->kurangProduk($request, $slug, 'all');
    }

    public function updateCart(Request $request)
    {
        $all_produks = $request->except('_token');

        $pesanan = $this->getCurrentPesanan();
        $pesanan->updatePesanan($all_produks);

        if ($request->wantsJson()) return ['message' => 'ok', 'data' => $pesanan];
        // beri alert
        alert()->success('Berhasil mengupdate data keranjang. ', 'Update Cart Success')->autoClose(3600);

        // kembalikan ke halaman sebelumnya 
        return back();
    }

    public function updateInfo(Request $request)
    {
        $pesanan = $this->getCurrentPesanan();
        // update info pesanan
        $info = $request->all();
        $pesanan->update($info);

        if ($request->wantsJson()) return ['message' => 'ok', 'data' => $pesanan];
        // beri alert
        alert()->success('Berhasil mengupdate data keranjang. ', 'Update Cart Success')->autoClose(3600);

        // kembalikan ke halaman sebelumnya 
        return back();
    }
}

app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use View;
use App\Produk;
use App\Kategori;
use App\Brand;
use App\Pesanan;
use App\Customer;
use App\MetodePembayaran;
use Illuminate\Http\Request as Request;
use App\BaseModel as Model;

class FrontendController extends BaseController
{
    protected $kategoris;
    protected $brands;
    protected $cart;
    protected $customer;

    public function __construct()
    {
        parent::__construct();
        $this->kategoris = Kategori::with(['produks' => function ($query) {
            $query->latest()->take(4);
        }])->get();
        $this->brands = Brand::with('produks')->get();
        $this->cart = request()->hasSession() && request()->session()->has('pesanan') ? Pesanan::with('produks', 'customer')->with('propinsi')->with('kota')->where('id', request()->session()->get('pesanan'))->first() : null;

        View::share('kategoris', $this->kategoris);
        View::share('brands', $this->brands);
        View::share('cart', $this->cart);
    }
}

resources/views/frontend/confirmPayment.blade.php
@extends('frontend')

@section('content')

	<section>
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="/">Home</a></li>
				  <li class="active" >Konfirmasi Pembayaran</li>
				</ol>
			</div>
			<div class="row">
				@include('partials.error')
			</div>
	@if(isset($pesanan))		
            <div class="shopper-informations">
				<div class="row">
					<div class="col-sm-5 col-sm-offset-1">
						<h4 class="text-center">
							Detail Pesanan - <strong>{{ $pesanan->kode_pesanan }}</strong>
							<br>
							<em><small>{{ ($tes = $pesanan->pembayaran && ! starts_with($pesanan->pembayaran->verified_at, '0000') && $pesanan->pembayaran->verified_at != null && $pesanan->status == 'dibayar') ? 'Lunas' : 'Menunggu Verifikasi'}}</small></em>
						</h4>
						<div class="cart-info">
							<div class="user_info">
								<div class="heading">
									<table class="table">
										<tbody>
											@foreach($pesanan->produks as $pesanan_produk)
											<tr>
												<td class="text-right">{{ $pesanan_produk->produk. ' x ' .$pesanan_produk->pivot->quantity }}</td>
												<td class="text-right">{{ 'Rp. '. number_format($pesanan_produk->pivot->jumlah, 0, ',', '.') }}</td>
											</tr>
											@endforeach
											<tr>
												<td class="text-right">Sub Total</td>
												<td class="text-right">{{ $pesanan->jumlah_rupiah }}</td>
											</tr>
											<tr>
												<td class="text-right">{{ $pesanan->ongkir == 0 ? 'Free Ongkir (Ambil di tempat)' : 'Ongkir' }}</td>
												<td class="text-right">{{ $pesanan->ongkir_rupiah }}</td>
											</tr>
											<tr>
												<td class="text-right">Total</td>
												<td class="text-right">{{ $pesanan->total_rupiah }}</td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-5">
			        	<div class="login-form"><!--login form-->
							@if($tes)
							<h2>Pesanan ini sudah Lunas</h2>
							@else
			                <h2>Masukkan Detail Pembayaran Anda</h2>
			                {!! Form::open(['url' => 'konfirmasi_pembayaran/'.$pesanan->kode_pesanan, 'files' => true]) !!}
								{!! Form::text('jumlah', null, ['class' => 'form-control', 'placeholder' => 'Jumlah Pembayaran']) !!}
								{!! Form::select('metode_pembayaran', [null => 'Pilih Metode Pembayaran'] + $metode_pembayarans, null, ['class' => 'form-control']) !!}
								<br>
								{!! Form::label('bukti', null, ['class' => 'control-label']) !!}
								{!! Form::file('bukti', null, ['class' => 'form-control']) !!}
			                    <button type="submit" class="btn btn-default">Kirim</button>
			                {!! Form::close() !!}
			                @endif
			            </div><!--/login form-->
					</div>
				</div>
			</div>
	@endif
			<div class="row">				
                <div class="col-sm-6 col-sm-offset-3">
                    <div class="login-form"><!--login form-->
                        <h2>Masukkan Nomor Pesanan Anda</h2>
                        {!! Form::open(['url' => 'konfirmasi_pembayaran']) !!}
                            <input type="text" name="no_pesanan" placeholder="No Pesanan Anda" />
                            <button type="submit" class="btn btn-default">Cari</button>
                        {!! Form::close() !!}
                    </div>
                </div>
			</div>
			<div class="row">
				<div class="space">&nbsp;</div>
			</div>
		</div>
	</section>

@stop

resources/views/frontend/home.blade.php
@extends('frontend')

@section('content')

	<section id="slider"><!--slider-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="1"></li>
							<li data-target="#slider-carousel" data-slide-to="2"></li>
						</ol>
						
						<div class="carousel-inner">
							@foreach($banners as $banner)
							<div class="item <?php if (!isset($numberBanner)) {echo 'active'; $numberBanner = 0; } ?>">
								<div class="col-sm-6">
									<h1>{{ $banner->produk }}</h1>
									<h2>{{ 'Rp '.number_format($banner->harga, 0, ',', '.') }}</h2>
									<p>{{ $banner->deskripsi }}</p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img src="{{ asset('/asset/produk/'.$banner->foto) }}" class="girl img-responsive" alt="" />
									<!-- <img src="images/home/pricing.png"  class="pricing" alt="" /> -->
								</div>
							</div>
							
							@endforeach	
						</div>
						
						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>
					
				</div>
			</div>
		</div>
	</section><!--/slider-->
	
	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					@include('partials.leftSideBar')
				</div>
				
				<div class="col-sm-9 padding-right">
					@include('partials.produkList')

					 <div class="features_items"><!--features_items-->
                        <p class="text-center">
                                <a href="/shop" class="btn btn-primary btn-lg">Lihat Semua Produk</a>
                        </p>
                        <p class="blank">&nbsp;</p>
                    </div>
					
				@if(isset($kategoris))	
					<div class="category-tab"><!--category-tab-->
						<div class="col-sm-12">
							<ul class="nav nav-tabs">
							<?php $firstK = 0; ?>
							@foreach($kategoris as $kategori)
							@if(count($kategori->produks))
								<li class="{{ 0 == $firstK++ ? 'active' : '' }}"><a href="#kategori-{{ str_slug($kategori->kategori) }}" data-toggle="tab">{{ $kategori->kategori }}</a></li>
							@endif
							@endforeach
							</ul>
						</div>
						<div class="tab-content">
							<?php $firstK = 0; ?>
							@foreach($kategoris as $kategori)
							@if(count($kategori->produks))
							<div class="tab-pane fade {{ 0 == $firstK++ ? 'active in' : '' }}" id="kategori-{{ str_slug($kategori->kategori) }}" >
								@foreach($kategori->produks as $produk)
								<div class="col-sm-3">
									<div class="single-products {{ ($produk->isSale) ? 'sale' : '' }}">
										<div class="productinfo text-center">
											<div class="img" style="background-image: url({{ asset('/asset/produk/'.$produk->foto) }});" title="{{ $produk->produk }}"></div>
											@if($produk->isSale)
											<h2>Rp. {{ $produk->harga_diskon_rupiah }}</h2>
											<h4><del>Rp. {{ $produk->harga_rupiah }}</del></h4>
											@else
											<h2>Rp. {{ $produk->harga_rupiah }}</h2>
											@endif
											<p class="product-name">{{ $produk->produk }}</p>
											<a href="{{ url('beli/'.$produk->slug) }}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div>
								</div>
								@endforeach
							</div>
							@endif
							@endforeach
						</div>
					</div><!--/category-tab-->
				@endif
				<!--	
					<div class="recommended_items">
						<h2 class="title text-center">recommended items</h2>
						
						<div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
							<div class="carousel-inner">
								<div class="item active">	
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend1.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>
												
											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend2.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>
												
											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend3.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>
												
											</div>
										</div>
									</div>
								</div>
								<div class="item">	
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend1.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>
												
											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend2.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>
												
											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend3.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>
												
											</div>
										</div>
									</div>
								</div>
							</div>
							 <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
								<i class="fa fa-angle-left"></i>
							  </a>
							  <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
								<i class="fa fa-angle-right"></i>
							  </a>			
						</div>
					</div>
				-->
				</div>
			</div>
		</div>
	</section>

@stop